@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle hollow
actor warehouseadmin
actor superuser
actor financialadmin
actor student
rectangle Warehouse {
    (seewarehouse) -- superuser  #line:purple;line.bold
    (order product) -- superuser  #line:purple;line.bold
    (request product) -- superuser  #line:purple;line.bold
    (approve orders) -- superuser  #line:purple;line.bold
    (seewarehouse) -- financialadmin  #line:blue;line.bold
    (approve orders) -- financialadmin  #line:blue;line.bold
    (seewarehouse) -- (warehouseadmin)  #line:black;line.bold
    (manage products) -- warehouseadmin  #line:black;line.bold
    student -- (request product)  #line:green;line.bold
    (take in products) .> (manage products)  : extends
    (send out products) .> (take in products)  : extends
}
@enduml