@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle hollow
actor warehouseadmin
actor superuser
actor financialadmin
actor student
rectangle seewarehouse {
    superuser -- (seewarehouse)
    superuser -- (order product)
    superuser -- (request product)
    superuser -- (approve orders)
    financialadmin -- (seewarehouse) 
    financialadmin -- (approve orders)
    (warehouseadmin) -- (seewarehouse)
    warehouseadmin -- (manage products)
    (request product) -- student
    (manage products) .> (take in products) : extends
    (take in products) .> (send out products) : extends
}
@enduml